services:
  registry:
    environment:
      REGISTRY_PROXY_USERNAME: ${REGISTRY_PROXY_USERNAME:?set REGISTRY_PROXY_USERNAME in .env}
      REGISTRY_PROXY_PASSWORD: ${REGISTRY_PROXY_PASSWORD:?set REGISTRY_PROXY_PASSWORD in .env}
